using minimumApi.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System.Diagnostics.CodeAnalysis;

namespace minimumApi.Migrations
{
    [DbContext(typeof(minimumApiDbContext))]
    [Migration("2001-InsertCountries_Data")]
    public class InsertCountries : Migration
    {
        protected override void Up([NotNull] MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(table: "Countries",
                                        schema: "dbo",
                                        columns: new string[] { "CountryName" },
                                        values: new object[,]
                                        {
                                            { "Türkiye" },
                                            { "ABD" },
                                            { "Afganistan"  },
                                            { "Almanya" },
                                            { "Amerikan Samoa"  },
                                            { "Andorra" },
                                            { "Angola"  },
                                            { "Anguilla"    },
                                            { "Antigua" },
                                            { "Arjantin"    },
                                            { "Arnavutluk"  },
                                            { "Aruba"   },
                                            { "Asension"    },
                                            { "Avustralya"  },
                                            { "Avusturya"   },
                                            { "Azerbaycan"  },
                                            { "Azor-Mader Adaları"  },
                                            { "BAE(Birleşik Arap Emirlikleri)"  },
                                            { "Bahama"  },
                                            { "Bahreyn" },
                                            { "Bangladeş"   },
                                            { "Barbados"    },
                                            { "Batı Samoa"  },
                                            { "Belçika" },
                                            { "Belize"  },
                                            { "Benin"   },
                                            { "Bermuda" },
                                            { "Beyaz Rusya" },
                                            { "Bolivya" },
                                            { "Bosna Hersek"    },
                                            { "Botsvana"    },
                                            { "Brezilya"    },
                                            { "British Virgin Adaları"  },
                                            { "Bruney"  },
                                            { "Bulgaristan" },
                                            { "Brkina Faso" },
                                            { "Burma"   },
                                            { "Burundi" },
                                            { "Butan"   },
                                            { "Cad" },
                                            { "Cebelitarık" },
                                            { "Çek Cumhuriyeti" },
                                            { "Cezayir" },
                                            { "Cibuti"  },
                                            { "Çin" },
                                            { "Cook Adası"  },
                                            { "Danimarka"   },
                                            { "Diego Garsia"    },
                                            { "Dominik" },
                                            { "Dominik Cumhuriyeti" },
                                            { "Ekvator" },
                                            { "Ekvator Girne"   },
                                            { "El Salvador" },
                                            { "Endonezya"   },
                                            { "Eritre"  },
                                            { "Erministan"  },
                                            { "Estonya" },
                                            { "Etiyopya"    },
                                            { "Falkland Adaları"    },
                                            { "Faroe Adaları"   },
                                            { "Fas" },
                                            { "Fiji"    },
                                            { "Fildişi Sahili"  },
                                            { "Filipinler"  },
                                            { "Finlandiya"  },
                                            { "Fransa"  },
                                            { "Fransız Guyanası"    },
                                            { "Fransız Polenazyası" },
                                            { "Gabon"   },
                                            { "Gambia"  },
                                            { "Gana"    },
                                            { "Gine"    },
                                            { "Gine Bissau" },
                                            { "Grenada" },
                                            { "Grönland"    },
                                            { "Guadalup"    },
                                            { "Guam"    },
                                            { "Guatemala"   },
                                            { "Güney Afrika Cumhuriyeti"    },
                                            { "Güney Kore"  },
                                            { "Gürcistan"   },
                                            { "Güyana"  },
                                            { "Haiti"   },
                                            { "Hindistan"   },
                                            { "Hırvatistan" },
                                            { "Hollanda"    },
                                            { "Hollanda Antilleri"  },
                                            { "Honduras"    },
                                            { "Hongkong"    },
                                            { "Irak"    },
                                            { "İngiltere"   },
                                            { "İran"    },
                                            { "İrlanda" },
                                            { "İspanya" },
                                            { "İsrail"  },
                                            { "İsveç"   },
                                            { "İsviçre" },
                                            { "İtalya"  },
                                            { "İzlanda" },
                                            { "Jamaika" },
                                            { "Japonya" },
                                            { "Kamboçya"    },
                                            { "Kamerun" },
                                            { "Kanada"  },
                                            { "Kap Verd"    },
                                            { "Katar"   },
                                            { "Kayman Adaları"  },
                                            { "Kazakistan"  },
                                            { "Kenya"   },
                                            { "Kırgızistan" },
                                            { "Kiribati"    },
                                            { "Kolombiya"   },
                                            { "Komor Adaları"   },
                                            { "Kongo"   },
                                            { "Kosta Rika"  },
                                            { "Küba"    },
                                            { "Kuveyt"  },
                                            { "Kuzey Kore"  },
                                            { "Lao Dem. Halk Cum."  },
                                            { "Lesotho" },
                                            { "Letonya" },
                                            { "Liberya" },
                                            { "Libya"   },
                                            { "Lihtenstayn" },
                                            { "Litvanya"    },
                                            { "Lübnan"  },
                                            { "Lüksemburg"  },
                                            { "Macaristan"  },
                                            { "Madagaskar"  },
                                            { "Makao"   },
                                            { "Makedonya"   },
                                            { "Malavi"  },
                                            { "Maldiv Adaları"  },
                                            { "Malezya" },
                                            { "Mali"    },
                                            { "Malta"   },
                                            { "Mariyan Adaları" },
                                            { "Malsar Adaları"  },
                                            { "Martinik"    },
                                            { "Meksika" },
                                            { "Merkezi Afrika Cum." },
                                            { "Mikronezya"  },
                                            { "Mısır"   },
                                            { "Moğolistan"  },
                                            { "Moldovya"    },
                                            { "Monaco"  },
                                            { "Montserrat"  },
                                            { "Moris Adaları"   },
                                            { "Moritanya"   },
                                            { "Mozambik"    },
                                            { "Nambiya" },
                                            { "Nauru Adası" },
                                            { "Nepal"   },
                                            { "Nijer"   },
                                            { "Nijerya" },
                                            { "Nikaragua"   },
                                            { "Niue Adaları"    },
                                            { "Norfolk Adaları" },
                                            { "Norveç"  },
                                            { "Özbekistan"  },
                                            { "Pakistan"    },
                                            { "Palau"   },
                                            { "Panama"  },
                                            { "Papua Yeni Gine" },
                                            { "Paraguay"    },
                                            { "Peru"    },
                                            { "Polonya" },
                                            { "Portekiz"    },
                                            { "Porto Riko"  },
                                            { "Radius"  },
                                            { "Reunyon" },
                                            { "Romanya" },
                                            { "Ruanda"  },
                                            { "Rusya Federasyonu"   },
                                            { "San Marino"  },
                                            { "Sao Tome&Principe"   },
                                            { "Senegal" },
                                            { "Seysel"  },
                                            { "Sierra Leone"    },
                                            { "Singapur"    },
                                            { "Slovak Cum." },
                                            { "Slovenya"    },
                                            { "Solomon Adaları" },
                                            { "Somali"  },
                                            { "Sri Lanka"   },
                                            { "St. Helena"  },
                                            { "St. Kittis&Nevis"    },
                                            { "St. Lucia"   },
                                            { "St. Marten"  },
                                            { "St. Piyer&Mikelon"   },
                                            { "St. Vincent&Grenada" },
                                            { "Sudan"   },
                                            { "Surinam" },
                                            { "Suriye"  },
                                            { "Suudi Arabistan" },
                                            { "Svaziland"   },
                                            { "Şili"    },
                                            { "Tacikistan"  },
                                            { "Tanzanya"    },
                                            { "Tataristan"  },
                                            { "Tatıncom"    },
                                            { "Taylan"  },
                                            { "Tayvan"  },
                                            { "Togo"    },
                                            { "Tokelan" },
                                            { "Tonga"   },
                                            { "Trinidad&Tobago" },
                                            { "Tunus"   },
                                            { "Türkmenistan"    },
                                            { "Turk&Caicos Adaları" },
                                            { "Tuvalu"  },
                                            { "U.S. Virgin Adası"   },
                                            { "Uganda"  },
                                            { "Ukrayna" },
                                            { "Umman"   },
                                            { "Urugay"  },
                                            { "Ürdün"   },
                                            { "Vallis Fununa Adaları"   },
                                            { "Venezuela"   },
                                            { "Vietnam" },
                                            { "Yemen Arap Cum." },
                                            { "Yemen Halk Cum." },
                                            { "Yeni Hebritler"  },
                                            { "Yeni Kaledonya"  },
                                            { "Yeni Zelenda"    },
                                            { "Yugoslavya"  },
                                            { "Yunanistan"  },
                                            { "Zaire"   },
                                            { "Zambiya" },
                                            { "Zanzibar"    },
                                            { "Zimbabve"    },
                                            { "Antarktika"  },
                                            { "Kongo (Dem. Cumhuriyeti)"    },
                                            { "Kıbrıs"  },
                                            { "Doğu Timor"  },
                                            { "Ext. Territ. Avustralya" },
                                            { "Guernsey ve Alderney"    },
                                            { "Jarse"   },
                                            { "Man Adası"   },
                                            { "Mayotte" },
                                            { "Filistin"    },
                                            { "Sahara"  },
                                            { "Sırbistan ve Karadağ"    },
                                            { "Smaller Territories of the UK"   },
                                            { "Svalbard ve Jan Mayen"   },
                                            { "Terres Australes"    },
                                            { "Vanuatu" },
                                            { "Vatikan" },
                                            { "Christmas Adası" },
                                            { "Curaçao" },
                                            { "Fransız Antilleri"   },
                                            { "Midway Adası"    }

                                        },
                                        columnTypes: new string[] { "varchar(100)" });
        }
    }
}
